---
default_language_version:
  python: python3.12

default_stages: [pre-commit]

repos:
  - repo: local
    hooks:
      - id: ruff-lint
        name: ruff-lint
        language: system
        entry: make lint
        types: ["python"]
