import pytest
from httpx import AsyncClient

from boaviztapi.main import app

pytest_plugins = ('pytest_asyncio',)


@pytest.mark.asyncio
async def test_complete_cpu():
    async with AsyncClient(app=app, base_url="http://test") as ac:
        res = await ac.post('/v1/component/cpu?verbose=false', json={"core_units": 12, "die_size_per_core": 24.5})

    assert res.json() == {'adp': {'description': 'Use of minerals and fossil ressources',
                                  'embedded': {'max': 0.02,
                                               'min': 0.02,
                                               'significant_figures': 2,
                                               'value': 0.02,
                                               'warnings': ['End of life is not included in the '
                                                            'calculation']},
                                  'unit': 'kgSbeq',
                                  'use': {'max': 0.0013,
                                          'min': 6.3e-05,
                                          'significant_figures': 2,
                                          'value': 0.00031}},
                          'gwp': {'description': 'Total climate change',
                                  'embedded': {'max': 15.9,
                                               'min': 15.9,
                                               'significant_figures': 3,
                                               'value': 15.9,
                                               'warnings': ['End of life is not included in the '
                                                            'calculation']},
                                  'unit': 'kgCO2eq',
                                  'use': {'max': 4300.0,
                                          'min': 110.0,
                                          'significant_figures': 2,
                                          'value': 1800.0}},
                          'pe': {'description': 'Consumption of primary energy',
                                 'embedded': {'max': 247.0,
                                              'min': 247.0,
                                              'significant_figures': 3,
                                              'value': 247.0,
                                              'warnings': ['End of life is not included in the '
                                                           'calculation']},
                                 'unit': 'MJ',
                                 'use': {'max': 2200000.0,
                                         'min': 62.0,
                                         'significant_figures': 2,
                                         'value': 62000.0}}}


@pytest.mark.asyncio
async def test_complete_cpu_verbose():
    async with AsyncClient(app=app, base_url="http://test") as ac:
        res = await ac.post('/v1/component/cpu?verbose=true', json={"core_units": 12, "die_size_per_core": 24.5})

    assert res.json() == {'impacts': {'adp': {'description': 'Use of minerals and fossil ressources',
                                              'embedded': {'max': 0.02,
                                                           'min': 0.02,
                                                           'significant_figures': 2,
                                                           'value': 0.02,
                                                           'warnings': ['End of life is not included in '
                                                                        'the calculation']},
                                              'unit': 'kgSbeq',
                                              'use': {'max': 0.0013,
                                                      'min': 6.3e-05,
                                                      'significant_figures': 2,
                                                      'value': 0.00031}},
                                      'gwp': {'description': 'Total climate change',
                                              'embedded': {'max': 15.9,
                                                           'min': 15.9,
                                                           'significant_figures': 3,
                                                           'value': 15.9,
                                                           'warnings': ['End of life is not included in '
                                                                        'the calculation']},
                                              'unit': 'kgCO2eq',
                                              'use': {'max': 4300.0,
                                                      'min': 110.0,
                                                      'significant_figures': 2,
                                                      'value': 1800.0}},
                                      'pe': {'description': 'Consumption of primary energy',
                                             'embedded': {'max': 247.0,
                                                          'min': 247.0,
                                                          'significant_figures': 3,
                                                          'value': 247.0,
                                                          'warnings': ['End of life is not included in '
                                                                       'the calculation']},
                                             'unit': 'MJ',
                                             'use': {'max': 2200000.0,
                                                     'min': 62.0,
                                                     'significant_figures': 2,
                                                     'value': 62000.0}}},
                          'verbose': {'adp_factor': {'max': 2.656e-07,
                                                     'min': 1.32e-08,
                                                     'source': 'ADEME Base IMPACTS ®',
                                                     'status': 'DEFAULT',
                                                     'unit': 'kg Sbeq/kWh',
                                                     'value': 6.42e-08},
                                      'avg_power': {'max': 182.22,
                                                    'min': 182.22,
                                                    'status': 'COMPLETED',
                                                    'unit': 'W',
                                                    'value': 182.22},
                                      'core_units': {'status': 'INPUT', 'value': 12},
                                      'die_size_per_core': {'status': 'INPUT',
                                                            'unit': 'cm2',
                                                            'value': 24.5},
                                      'duration': {'unit': 'hours', 'value': 26280.0},
                                      'gwp_factor': {'max': 0.9,
                                                     'min': 0.023,
                                                     'source': 'https://www.sciencedirect.com/science/article/pii/S0306261921012149: \n'
                                                               'Average of 27 european countries',
                                                     'status': 'DEFAULT',
                                                     'unit': 'kg CO2eq/kWh',
                                                     'value': 0.38},
                                      'hours_life_time': {'max': 26280.0,
                                                          'min': 26280.0,
                                                          'status': 'ARCHETYPE',
                                                          'unit': 'hours',
                                                          'value': 26280.0},
                                      'impacts': {'adp': {'description': 'Use of minerals and fossil '
                                                                         'ressources',
                                                          'embedded': {'max': 0.02,
                                                                       'min': 0.02,
                                                                       'significant_figures': 2,
                                                                       'value': 0.02,
                                                                       'warnings': ['End of life is not '
                                                                                    'included in the '
                                                                                    'calculation']},
                                                          'unit': 'kgSbeq',
                                                          'use': {'max': 0.0013,
                                                                  'min': 6.3e-05,
                                                                  'significant_figures': 2,
                                                                  'value': 0.00031}},
                                                  'gwp': {'description': 'Total climate change',
                                                          'embedded': {'max': 15.9,
                                                                       'min': 15.9,
                                                                       'significant_figures': 3,
                                                                       'value': 15.9,
                                                                       'warnings': ['End of life is not '
                                                                                    'included in the '
                                                                                    'calculation']},
                                                          'unit': 'kgCO2eq',
                                                          'use': {'max': 4300.0,
                                                                  'min': 110.0,
                                                                  'significant_figures': 2,
                                                                  'value': 1800.0}},
                                                  'pe': {'description': 'Consumption of primary energy',
                                                         'embedded': {'max': 247.0,
                                                                      'min': 247.0,
                                                                      'significant_figures': 3,
                                                                      'value': 247.0,
                                                                      'warnings': ['End of life is not '
                                                                                   'included in the '
                                                                                   'calculation']},
                                                         'unit': 'MJ',
                                                         'use': {'max': 2200000.0,
                                                                 'min': 62.0,
                                                                 'significant_figures': 2,
                                                                 'value': 62000.0}}},
                                      'model_range': {'status': 'ARCHETYPE', 'value': 'Xeon Platinum'},
                                      'params': {'source': 'From CPU model range',
                                                 'status': 'COMPLETED',
                                                 'value': {'a': 171.1813,
                                                           'b': 0.0354,
                                                           'c': 36.8953,
                                                           'd': -10.1336}},
                                      'pe_factor': {'max': 468.15,
                                                    'min': 0.013,
                                                    'source': 'ADPf / (1-%renewable_energy)',
                                                    'status': 'DEFAULT',
                                                    'unit': 'MJ/kWh',
                                                    'value': 12.874},
                                      'time_workload': {'max': 100.0,
                                                        'min': 0.0,
                                                        'status': 'ARCHETYPE',
                                                        'unit': '%',
                                                        'value': 50.0},
                                      'units': {'max': 1.0,
                                                'min': 1.0,
                                                'status': 'ARCHETYPE',
                                                'value': 1.0},
                                      'usage_location': {'status': 'DEFAULT',
                                                         'unit': 'CodSP3 - NCS Country Codes - NATO',
                                                         'value': 'EEE'},
                                      'use_time_ratio': {'max': 1.0,
                                                         'min': 1.0,
                                                         'status': 'ARCHETYPE',
                                                         'unit': '/1',
                                                         'value': 1.0}}}


@pytest.mark.asyncio
async def test_complete_cpu_with_low_precision():
    async with AsyncClient(app=app, base_url="http://test") as ac:
        res = await ac.post('/v1/component/cpu?verbose=false', json={"core_units": 12, "die_size_per_core": 20.0})

    assert res.json() == {'adp': {'description': 'Use of minerals and fossil ressources',
                                  'embedded': {'max': 0.02,
                                               'min': 0.02,
                                               'significant_figures': 2,
                                               'value': 0.02,
                                               'warnings': ['End of life is not included in the '
                                                            'calculation']},
                                  'unit': 'kgSbeq',
                                  'use': {'max': 0.0013,
                                          'min': 6.3e-05,
                                          'significant_figures': 2,
                                          'value': 0.00031}},
                          'gwp': {'description': 'Total climate change',
                                  'embedded': {'max': 15.0,
                                               'min': 15.0,
                                               'significant_figures': 2,
                                               'value': 15.0,
                                               'warnings': ['End of life is not included in the '
                                                            'calculation']},
                                  'unit': 'kgCO2eq',
                                  'use': {'max': 4300.0,
                                          'min': 110.0,
                                          'significant_figures': 2,
                                          'value': 1800.0}},
                          'pe': {'description': 'Consumption of primary energy',
                                 'embedded': {'max': 230.0,
                                              'min': 230.0,
                                              'significant_figures': 2,
                                              'value': 230.0,
                                              'warnings': ['End of life is not included in the '
                                                           'calculation']},
                                 'unit': 'MJ',
                                 'use': {'max': 2200000.0,
                                         'min': 62.0,
                                         'significant_figures': 2,
                                         'value': 62000.0}}}


@pytest.mark.asyncio
async def test_empty_cpu():
    async with AsyncClient(app=app, base_url="http://test") as ac:
        res = await ac.post('/v1/component/cpu?verbose=false', json={})

    assert res.json() == {'adp': {'description': 'Use of minerals and fossil ressources',
                                  'embedded': {'max': 0.02,
                                               'min': 0.02,
                                               'significant_figures': 2,
                                               'value': 0.02,
                                               'warnings': ['End of life is not included in the '
                                                            'calculation']},
                                  'unit': 'kgSbeq',
                                  'use': {'max': 0.0013,
                                          'min': 6.3e-05,
                                          'significant_figures': 2,
                                          'value': 0.00031}},
                          'gwp': {'description': 'Total climate change',
                                  'embedded': {'max': 22.7,
                                               'min': 11.1,
                                               'significant_figures': 3,
                                               'value': 21.7,
                                               'warnings': ['End of life is not included in the '
                                                            'calculation']},
                                  'unit': 'kgCO2eq',
                                  'use': {'max': 4300.0,
                                          'min': 110.0,
                                          'significant_figures': 2,
                                          'value': 1800.0}},
                          'pe': {'description': 'Consumption of primary energy',
                                 'embedded': {'max': 339.0,
                                              'min': 182.0,
                                              'significant_figures': 3,
                                              'value': 325.0,
                                              'warnings': ['End of life is not included in the '
                                                           'calculation']},
                                 'unit': 'MJ',
                                 'use': {'max': 2200000.0,
                                         'min': 62.0,
                                         'significant_figures': 2,
                                         'value': 62000.0}}}


@pytest.mark.asyncio
async def test_multiple_cpu():
    async with AsyncClient(app=app, base_url="http://test") as ac:
        res = await ac.post('/v1/component/cpu?verbose=false', json={
            "units": 3, "core_units": 12, "die_size_per_core": 24.5})

    assert res.json() == {'adp': {'description': 'Use of minerals and fossil ressources',
                                  'embedded': {'max': 0.061,
                                               'min': 0.061,
                                               'significant_figures': 2,
                                               'value': 0.061,
                                               'warnings': ['End of life is not included in the '
                                                            'calculation']},
                                  'unit': 'kgSbeq',
                                  'use': {'max': 0.0038,
                                          'min': 0.00019,
                                          'significant_figures': 2,
                                          'value': 0.00092}},
                          'gwp': {'description': 'Total climate change',
                                  'embedded': {'max': 47.7,
                                               'min': 47.7,
                                               'significant_figures': 3,
                                               'value': 47.7,
                                               'warnings': ['End of life is not included in the '
                                                            'calculation']},
                                  'unit': 'kgCO2eq',
                                  'use': {'max': 13000.0,
                                          'min': 330.0,
                                          'significant_figures': 2,
                                          'value': 5500.0}},
                          'pe': {'description': 'Consumption of primary energy',
                                 'embedded': {'max': 741.0,
                                              'min': 741.0,
                                              'significant_figures': 3,
                                              'value': 741.0,
                                              'warnings': ['End of life is not included in the '
                                                           'calculation']},
                                 'unit': 'MJ',
                                 'use': {'max': 6700000.0,
                                         'min': 190.0,
                                         'significant_figures': 2,
                                         'value': 180000.0}}}


@pytest.mark.asyncio
async def test_incomplete_cpu_verbose():
    async with AsyncClient(app=app, base_url="http://test") as ac:
        res = await ac.post('/v1/component/cpu?verbose=true', json={
            "core_units": 24, "family": "Skylake"})

    assert res.json() == {'impacts': {'adp': {'description': 'Use of minerals and fossil ressources',
                                              'embedded': {'max': 0.02,
                                                           'min': 0.02,
                                                           'significant_figures': 2,
                                                           'value': 0.02,
                                                           'warnings': ['End of life is not included in '
                                                                        'the calculation']},
                                              'unit': 'kgSbeq',
                                              'use': {'max': 0.0013,
                                                      'min': 6.3e-05,
                                                      'significant_figures': 2,
                                                      'value': 0.00031}},
                                      'gwp': {'description': 'Total climate change',
                                              'embedded': {'max': 23.0,
                                                           'min': 22.0,
                                                           'significant_figures': 2,
                                                           'value': 22.0,
                                                           'warnings': ['End of life is not included in '
                                                                        'the calculation']},
                                              'unit': 'kgCO2eq',
                                              'use': {'max': 4300.0,
                                                      'min': 110.0,
                                                      'significant_figures': 2,
                                                      'value': 1800.0}},
                                      'pe': {'description': 'Consumption of primary energy',
                                             'embedded': {'max': 340.0,
                                                          'min': 330.0,
                                                          'significant_figures': 2,
                                                          'value': 330.0,
                                                          'warnings': ['End of life is not included in '
                                                                       'the calculation']},
                                             'unit': 'MJ',
                                             'use': {'max': 2200000.0,
                                                     'min': 62.0,
                                                     'significant_figures': 2,
                                                     'value': 62000.0}}},
                          'verbose': {'adp_factor': {'max': 2.656e-07,
                                                     'min': 1.32e-08,
                                                     'source': 'ADEME Base IMPACTS ®',
                                                     'status': 'DEFAULT',
                                                     'unit': 'kg Sbeq/kWh',
                                                     'value': 6.42e-08},
                                      'avg_power': {'max': 182.22,
                                                    'min': 182.22,
                                                    'status': 'COMPLETED',
                                                    'unit': 'W',
                                                    'value': 182.22},
                                      'core_units': {'status': 'INPUT', 'value': 24},
                                      'die_size_per_core': {'max': 0.27,
                                                            'min': 0.25,
                                                            'source': 'https://en.wikichip.org/wiki/intel/microarchitectures/skylake_(server)#Extreme_Core_Count_.28XCC.29',
                                                            'status': 'COMPLETED',
                                                            'unit': 'cm2',
                                                            'value': 0.25},
                                      'duration': {'unit': 'hours', 'value': 26280.0},
                                      'family': {'status': 'CHANGED', 'value': 'skylake'},
                                      'gwp_factor': {'max': 0.9,
                                                     'min': 0.023,
                                                     'source': 'https://www.sciencedirect.com/science/article/pii/S0306261921012149: \n'
                                                               'Average of 27 european countries',
                                                     'status': 'DEFAULT',
                                                     'unit': 'kg CO2eq/kWh',
                                                     'value': 0.38},
                                      'hours_life_time': {'max': 26280.0,
                                                          'min': 26280.0,
                                                          'status': 'ARCHETYPE',
                                                          'unit': 'hours',
                                                          'value': 26280.0},
                                      'impacts': {'adp': {'description': 'Use of minerals and fossil '
                                                                         'ressources',
                                                          'embedded': {'max': 0.02,
                                                                       'min': 0.02,
                                                                       'significant_figures': 2,
                                                                       'value': 0.02,
                                                                       'warnings': ['End of life is not '
                                                                                    'included in the '
                                                                                    'calculation']},
                                                          'unit': 'kgSbeq',
                                                          'use': {'max': 0.0013,
                                                                  'min': 6.3e-05,
                                                                  'significant_figures': 2,
                                                                  'value': 0.00031}},
                                                  'gwp': {'description': 'Total climate change',
                                                          'embedded': {'max': 23.0,
                                                                       'min': 22.0,
                                                                       'significant_figures': 2,
                                                                       'value': 22.0,
                                                                       'warnings': ['End of life is not '
                                                                                    'included in the '
                                                                                    'calculation']},
                                                          'unit': 'kgCO2eq',
                                                          'use': {'max': 4300.0,
                                                                  'min': 110.0,
                                                                  'significant_figures': 2,
                                                                  'value': 1800.0}},
                                                  'pe': {'description': 'Consumption of primary energy',
                                                         'embedded': {'max': 340.0,
                                                                      'min': 330.0,
                                                                      'significant_figures': 2,
                                                                      'value': 330.0,
                                                                      'warnings': ['End of life is not '
                                                                                   'included in the '
                                                                                   'calculation']},
                                                         'unit': 'MJ',
                                                         'use': {'max': 2200000.0,
                                                                 'min': 62.0,
                                                                 'significant_figures': 2,
                                                                 'value': 62000.0}}},
                                      'model_range': {'status': 'ARCHETYPE', 'value': 'Xeon Platinum'},
                                      'params': {'source': 'From CPU model range',
                                                 'status': 'COMPLETED',
                                                 'value': {'a': 171.1813,
                                                           'b': 0.0354,
                                                           'c': 36.8953,
                                                           'd': -10.1336}},
                                      'pe_factor': {'max': 468.15,
                                                    'min': 0.013,
                                                    'source': 'ADPf / (1-%renewable_energy)',
                                                    'status': 'DEFAULT',
                                                    'unit': 'MJ/kWh',
                                                    'value': 12.874},
                                      'time_workload': {'max': 100.0,
                                                        'min': 0.0,
                                                        'status': 'ARCHETYPE',
                                                        'unit': '%',
                                                        'value': 50.0},
                                      'units': {'max': 1.0,
                                                'min': 1.0,
                                                'status': 'ARCHETYPE',
                                                'value': 1.0},
                                      'usage_location': {'status': 'DEFAULT',
                                                         'unit': 'CodSP3 - NCS Country Codes - NATO',
                                                         'value': 'EEE'},
                                      'use_time_ratio': {'max': 1.0,
                                                         'min': 1.0,
                                                         'status': 'ARCHETYPE',
                                                         'unit': '/1',
                                                         'value': 1.0}}}


@pytest.mark.asyncio
async def test_incomplete_cpu_verbose_2():
    async with AsyncClient(app=app, base_url="http://test") as ac:
        res = await ac.post('/v1/component/cpu?verbose=true', json={
            "core_units": 24, "family": "skylak"})

    assert res.json() == {'impacts': {'adp': {'description': 'Use of minerals and fossil ressources',
                                              'embedded': {'max': 0.02,
                                                           'min': 0.02,
                                                           'significant_figures': 2,
                                                           'value': 0.02,
                                                           'warnings': ['End of life is not included in '
                                                                        'the calculation']},
                                              'unit': 'kgSbeq',
                                              'use': {'max': 0.0013,
                                                      'min': 6.3e-05,
                                                      'significant_figures': 2,
                                                      'value': 0.00031}},
                                      'gwp': {'description': 'Total climate change',
                                              'embedded': {'max': 23.0,
                                                           'min': 22.0,
                                                           'significant_figures': 2,
                                                           'value': 22.0,
                                                           'warnings': ['End of life is not included in '
                                                                        'the calculation']},
                                              'unit': 'kgCO2eq',
                                              'use': {'max': 4300.0,
                                                      'min': 110.0,
                                                      'significant_figures': 2,
                                                      'value': 1800.0}},
                                      'pe': {'description': 'Consumption of primary energy',
                                             'embedded': {'max': 340.0,
                                                          'min': 330.0,
                                                          'significant_figures': 2,
                                                          'value': 330.0,
                                                          'warnings': ['End of life is not included in '
                                                                       'the calculation']},
                                             'unit': 'MJ',
                                             'use': {'max': 2200000.0,
                                                     'min': 62.0,
                                                     'significant_figures': 2,
                                                     'value': 62000.0}}},
                          'verbose': {'adp_factor': {'max': 2.656e-07,
                                                     'min': 1.32e-08,
                                                     'source': 'ADEME Base IMPACTS ®',
                                                     'status': 'DEFAULT',
                                                     'unit': 'kg Sbeq/kWh',
                                                     'value': 6.42e-08},
                                      'avg_power': {'max': 182.22,
                                                    'min': 182.22,
                                                    'status': 'COMPLETED',
                                                    'unit': 'W',
                                                    'value': 182.22},
                                      'core_units': {'status': 'INPUT', 'value': 24},
                                      'die_size_per_core': {'max': 0.27,
                                                            'min': 0.25,
                                                            'source': 'https://en.wikichip.org/wiki/intel/microarchitectures/skylake_(server)#Extreme_Core_Count_.28XCC.29',
                                                            'status': 'COMPLETED',
                                                            'unit': 'cm2',
                                                            'value': 0.25},
                                      'duration': {'unit': 'hours', 'value': 26280.0},
                                      'family': {'status': 'CHANGED', 'value': 'skylake'},
                                      'gwp_factor': {'max': 0.9,
                                                     'min': 0.023,
                                                     'source': 'https://www.sciencedirect.com/science/article/pii/S0306261921012149: \n'
                                                               'Average of 27 european countries',
                                                     'status': 'DEFAULT',
                                                     'unit': 'kg CO2eq/kWh',
                                                     'value': 0.38},
                                      'hours_life_time': {'max': 26280.0,
                                                          'min': 26280.0,
                                                          'status': 'ARCHETYPE',
                                                          'unit': 'hours',
                                                          'value': 26280.0},
                                      'impacts': {'adp': {'description': 'Use of minerals and fossil '
                                                                         'ressources',
                                                          'embedded': {'max': 0.02,
                                                                       'min': 0.02,
                                                                       'significant_figures': 2,
                                                                       'value': 0.02,
                                                                       'warnings': ['End of life is not '
                                                                                    'included in the '
                                                                                    'calculation']},
                                                          'unit': 'kgSbeq',
                                                          'use': {'max': 0.0013,
                                                                  'min': 6.3e-05,
                                                                  'significant_figures': 2,
                                                                  'value': 0.00031}},
                                                  'gwp': {'description': 'Total climate change',
                                                          'embedded': {'max': 23.0,
                                                                       'min': 22.0,
                                                                       'significant_figures': 2,
                                                                       'value': 22.0,
                                                                       'warnings': ['End of life is not '
                                                                                    'included in the '
                                                                                    'calculation']},
                                                          'unit': 'kgCO2eq',
                                                          'use': {'max': 4300.0,
                                                                  'min': 110.0,
                                                                  'significant_figures': 2,
                                                                  'value': 1800.0}},
                                                  'pe': {'description': 'Consumption of primary energy',
                                                         'embedded': {'max': 340.0,
                                                                      'min': 330.0,
                                                                      'significant_figures': 2,
                                                                      'value': 330.0,
                                                                      'warnings': ['End of life is not '
                                                                                   'included in the '
                                                                                   'calculation']},
                                                         'unit': 'MJ',
                                                         'use': {'max': 2200000.0,
                                                                 'min': 62.0,
                                                                 'significant_figures': 2,
                                                                 'value': 62000.0}}},
                                      'model_range': {'status': 'ARCHETYPE', 'value': 'Xeon Platinum'},
                                      'params': {'source': 'From CPU model range',
                                                 'status': 'COMPLETED',
                                                 'value': {'a': 171.1813,
                                                           'b': 0.0354,
                                                           'c': 36.8953,
                                                           'd': -10.1336}},
                                      'pe_factor': {'max': 468.15,
                                                    'min': 0.013,
                                                    'source': 'ADPf / (1-%renewable_energy)',
                                                    'status': 'DEFAULT',
                                                    'unit': 'MJ/kWh',
                                                    'value': 12.874},
                                      'time_workload': {'max': 100.0,
                                                        'min': 0.0,
                                                        'status': 'ARCHETYPE',
                                                        'unit': '%',
                                                        'value': 50.0},
                                      'units': {'max': 1.0,
                                                'min': 1.0,
                                                'status': 'ARCHETYPE',
                                                'value': 1.0},
                                      'usage_location': {'status': 'DEFAULT',
                                                         'unit': 'CodSP3 - NCS Country Codes - NATO',
                                                         'value': 'EEE'},
                                      'use_time_ratio': {'max': 1.0,
                                                         'min': 1.0,
                                                         'status': 'ARCHETYPE',
                                                         'unit': '/1',
                                                         'value': 1.0}}}


@pytest.mark.asyncio
async def test_complete_ram():
    async with AsyncClient(app=app, base_url="http://test") as ac:
        res = await ac.post('/v1/component/ram?verbose=false', json={"units": 12, "capacity": 32, "density": 1.79})

    assert res.json() == {'adp': {'description': 'Use of minerals and fossil ressources',
                                  'embedded': {'max': 0.034,
                                               'min': 0.034,
                                               'significant_figures': 2,
                                               'value': 0.034,
                                               'warnings': ['End of life is not included in the '
                                                            'calculation']},
                                  'unit': 'kgSbeq',
                                  'use': {'max': 0.00076,
                                          'min': 3.8e-05,
                                          'significant_figures': 2,
                                          'value': 0.00018}},
                          'gwp': {'description': 'Total climate change',
                                  'embedded': {'max': 530.0,
                                               'min': 530.0,
                                               'significant_figures': 2,
                                               'value': 530.0,
                                               'warnings': ['End of life is not included in the '
                                                            'calculation']},
                                  'unit': 'kgCO2eq',
                                  'use': {'max': 2600.0,
                                          'min': 66.0,
                                          'significant_figures': 2,
                                          'value': 1100.0}},
                          'pe': {'description': 'Consumption of primary energy',
                                 'embedded': {'max': 6700.0,
                                              'min': 6700.0,
                                              'significant_figures': 2,
                                              'value': 6700.0,
                                              'warnings': ['End of life is not included in the '
                                                           'calculation']},
                                 'unit': 'MJ',
                                 'use': {'max': 1300000.0,
                                         'min': 37.0,
                                         'significant_figures': 2,
                                         'value': 37000.0}}}


@pytest.mark.asyncio
async def test_empty_ram():
    async with AsyncClient(app=app, base_url="http://test") as ac:
        res = await ac.post('/v1/component/ram?verbose=false', json={})

    assert res.json() == {'adp': {'description': 'Use of minerals and fossil ressources',
                                  'embedded': {'max': 0.065,
                                               'min': 0.0018,
                                               'significant_figures': 2,
                                               'value': 0.0049,
                                               'warnings': ['End of life is not included in the '
                                                            'calculation']},
                                  'unit': 'kgSbeq',
                                  'use': {'max': 6.3e-05,
                                          'min': 3.2e-06,
                                          'significant_figures': 2,
                                          'value': 1.5e-05}},
                          'gwp': {'description': 'Total climate change',
                                  'embedded': {'max': 2200.0,
                                               'min': 7.4,
                                               'significant_figures': 2,
                                               'value': 120.0,
                                               'warnings': ['End of life is not included in the '
                                                            'calculation']},
                                  'unit': 'kgCO2eq',
                                  'use': {'max': 210.0,
                                          'min': 5.5,
                                          'significant_figures': 2,
                                          'value': 91.0}},
                          'pe': {'description': 'Consumption of primary energy',
                                 'embedded': {'max': 27000.0,
                                              'min': 100.0,
                                              'significant_figures': 2,
                                              'value': 1500.0,
                                              'warnings': ['End of life is not included in the '
                                                           'calculation']},
                                 'unit': 'MJ',
                                 'use': {'max': 110000.0,
                                         'min': 3.1,
                                         'significant_figures': 2,
                                         'value': 3100.0}}}


@pytest.mark.asyncio
async def test_complete_ssd():
    async with AsyncClient(app=app, base_url="http://test") as ac:
        res = await ac.post('/v1/component/ssd?verbose=false', json={"capacity": 400, "density": 50.6})

    assert res.json() == {'adp': {'description': 'Use of minerals and fossil ressources',
                                  'embedded': {'warnings': ['End of life is not included in the calculation'],
                                               'max': 0.0011,
                                               'min': 0.0011,
                                               'significant_figures': 2,
                                               'value': 0.0011},
                                  'unit': 'kgSbeq',
                                  'use': 'not implemented'},
                          'gwp': {'description': 'Total climate change',
                                  'embedded': {'warnings': ['End of life is not included in the calculation'],
                                               'max': 24.0,
                                               'min': 24.0,
                                               'significant_figures': 2,
                                               'value': 24.0},
                                  'unit': 'kgCO2eq',
                                  'use': 'not implemented'},
                          'pe': {'description': 'Consumption of primary energy',
                                 'embedded': {'warnings': ['End of life is not included in the calculation'],
                                              'max': 293.0,
                                              'min': 293.0,
                                              'significant_figures': 3,
                                              'value': 293.0},
                                 'unit': 'MJ',
                                 'use': 'not implemented'}}


@pytest.mark.asyncio
async def test_empty_ssd():
    async with AsyncClient(app=app, base_url="http://test") as ac:
        res = await ac.post('/v1/component/ssd?verbose=false', json={})

    assert res.json() == {'adp': {'description': 'Use of minerals and fossil ressources',
                                  'embedded': {'warnings': ['End of life is not included in the calculation'],
                                               'max': 3.2,
                                               'min': 0.0069,
                                               'significant_figures': 2,
                                               'value': 0.0019},
                                  'unit': 'kgSbeq',
                                  'use': 'not implemented'},
                          'gwp': {'description': 'Total climate change',
                                  'embedded': {'warnings': ['End of life is not included in the calculation'],
                                               'max': 110000.0,
                                               'min': 230.0,
                                               'significant_figures': 2,
                                               'value': 52.0},
                                  'unit': 'kgCO2eq',
                                  'use': 'not implemented'},
                          'pe': {'description': 'Consumption of primary energy',
                                 'embedded': {'warnings': ['End of life is not included in the calculation'],
                                              'max': 1370000.0,
                                              'min': 2810.0,
                                              'significant_figures': 3,
                                              'value': 640.0},
                                 'unit': 'MJ',
                                 'use': 'not implemented'}}


@pytest.mark.asyncio
async def test_empty_blade():
    async with AsyncClient(app=app, base_url="http://test") as ac:
        res = await ac.post('/v1/component/case?verbose=false', json={"case_type": "blade"})

    assert res.json() == {'adp': {'description': 'Use of minerals and fossil ressources',
                                  'embedded': {'warnings': ['End of life is not included in the calculation'],
                                               'max': 0.0277,
                                               'min': 0.0277,
                                               'significant_figures': 3,
                                               'value': 0.0277},
                                  'unit': 'kgSbeq',
                                  'use': 'not implemented'},
                          'gwp': {'description': 'Total climate change',
                                  'embedded': {'warnings': ['End of life is not included in the calculation'],
                                               'max': 85.9,
                                               'min': 85.9,
                                               'significant_figures': 3,
                                               'value': 85.9},
                                  'unit': 'kgCO2eq',
                                  'use': 'not implemented'},
                          'pe': {'description': 'Consumption of primary energy',
                                 'embedded': {'warnings': ['End of life is not included in the calculation'],
                                              'max': 1230.0,
                                              'min': 1230.0,
                                              'significant_figures': 3,
                                              'value': 1230.0},
                                 'unit': 'MJ',
                                 'use': 'not implemented'}}
