from boaviztapi.service.allocation import Allocation
from boaviztapi.service.bottom_up import bottom_up


def test_bottom_up_component_cpu_empty(empty_cpu_model):
    assert bottom_up(empty_cpu_model, allocation=Allocation.TOTAL) == \
           {'adp': {'description': 'Use of minerals and fossil ressources',
                    'embedded': {'max': 0.02,
                                    'min': 0.02,
                                    'significant_figures': 2,
                                    'value': 0.02},
                    'unit': 'kgSbeq',
                    'use': {'max': 0.00424,
                            'min': 2.41e-09,
                            'significant_figures': 3,
                            'value': 0.000102}},
            'gwp': {'description': 'Total climate change',
                    'embedded': {'max': 22.7,
                                    'min': 11.1,
                                    'significant_figures': 3,
                                    'value': 21.7},
                    'unit': 'kgCO2eq',
                    'use': {'max': 14000.0,
                            'min': 0.0042,
                            'significant_figures': 2,
                            'value': 610.0}},
            'pe': {'description': 'Consumption of primary energy',
                   'embedded': {'max': 339.0,
                                   'min': 182.0,
                                   'significant_figures': 3,
                                   'value': 325.0},
                   'unit': 'MJ',
                   'use': {'max': 7473000.0,
                           'min': 0.002369,
                           'significant_figures': 4,
                           'value': 20550.0}}}

def test_bottom_up_component_cpu_complete(complete_cpu_model):
    assert bottom_up(complete_cpu_model, allocation=Allocation.TOTAL) == \
           {'adp': {'description': 'Use of minerals and fossil ressources',
                    'embedded': {'max': 0.041,
                                 'min': 0.041,
                                 'significant_figures': 2,
                                 'value': 0.041},
                    'unit': 'kgSbeq',
                    'use': {'max': 0.00848,
                            'min': 4.81e-09,
                            'significant_figures': 3,
                            'value': 0.000205}},
            'gwp': {'description': 'Total climate change',
                    'embedded': {'max': 43.4,
                                 'min': 43.4,
                                 'significant_figures': 3,
                                 'value': 43.4},
                    'unit': 'kgCO2eq',
                    'use': {'max': 29000.0,
                            'min': 0.0084,
                            'significant_figures': 2,
                            'value': 1200.0}},
            'pe': {'description': 'Consumption of primary energy',
                   'embedded': {'max': 650.0,
                                'min': 650.0,
                                'significant_figures': 3,
                                'value': 650.0},
                   'unit': 'MJ',
                   'use': {'max': 14950000.0,
                           'min': 0.004738,
                           'significant_figures': 4,
                           'value': 41100.0}}}


def test_bottom_up_component_cpu_incomplete(incomplete_cpu_model):
    bottom_up(incomplete_cpu_model, allocation=Allocation.TOTAL)
    print(incomplete_cpu_model.usage.hours_electrical_consumption.value)
    assert bottom_up(incomplete_cpu_model, allocation=Allocation.TOTAL) == \
           {'adp': {'description': 'Use of minerals and fossil ressources',
                    'embedded': {'max': 0.02,
                                 'min': 0.02,
                                 'significant_figures': 2,
                                 'value': 0.02},
                    'unit': 'kgSbeq',
                    'use': {'max': 0.00424,
                            'min': 2.41e-09,
                            'significant_figures': 3,
                            'value': 0.000102}},
            'gwp': {'description': 'Total climate change',
                    'embedded': {'max': 19.7,
                                 'min': 19.7,
                                 'significant_figures': 3,
                                 'value': 19.7},
                    'unit': 'kgCO2eq',
                    'use': {'max': 14000.0,
                            'min': 0.0042,
                            'significant_figures': 2,
                            'value': 610.0}},
            'pe': {'description': 'Consumption of primary energy',
                   'embedded': {'max': 297.0,
                                'min': 297.0,
                                'significant_figures': 3,
                                'value': 297.0},
                   'unit': 'MJ',
                   'use': {'max': 7473000.0,
                           'min': 0.002369,
                           'significant_figures': 4,
                           'value': 20550.0}}}


def test_bottom_up_component_ssd_empty(empty_ssd_model):
    assert bottom_up(empty_ssd_model, allocation=Allocation.TOTAL) == \
           {'adp': {'description': 'Use of minerals and fossil ressources',
                    'embedded': {'max': 3.2,
                                 'min': 0.0069,
                                 'significant_figures': 2,
                                 'value': 0.0019},
                    'unit': 'kgSbeq',
                    'use': 'not implemented'},
            'gwp': {'description': 'Total climate change',
                    'embedded': {'max': 110000.0,
                                 'min': 230.0,
                                 'significant_figures': 2,
                                 'value': 52.0},
                    'unit': 'kgCO2eq',
                    'use': 'not implemented'},
            'pe': {'description': 'Consumption of primary energy',
                   'embedded': {'max': 1370000.0,
                                'min': 2810.0,
                                'significant_figures': 3,
                                'value': 640.0},
                   'unit': 'MJ',
                   'use': 'not implemented'}}


def test_bottom_up_component_ssd_complete(complete_ssd_model):
    assert bottom_up(complete_ssd_model, allocation=Allocation.TOTAL) == \
           {'adp': {'description': 'Use of minerals and fossil ressources',
                    'embedded': {'max': 0.0011,
                                 'min': 0.0011,
                                 'significant_figures': 2,
                                 'value': 0.0011},
                    'unit': 'kgSbeq',
                    'use': 'not implemented'},
            'gwp': {'description': 'Total climate change',
                    'embedded': {'max': 24.0,
                                 'min': 24.0,
                                 'significant_figures': 2,
                                 'value': 24.0},
                    'unit': 'kgCO2eq',
                    'use': 'not implemented'},
            'pe': {'description': 'Consumption of primary energy',
                   'embedded': {'max': 293.0,
                                'min': 293.0,
                                'significant_figures': 3,
                                'value': 293.0},
                   'unit': 'MJ',
                   'use': 'not implemented'}}


def test_bottom_up_component_ssd_incomplete(incomplete_ssd_model):
    assert bottom_up(incomplete_ssd_model, allocation=Allocation.TOTAL) == \
           {'adp': {'description': 'Use of minerals and fossil ressources',
                    'embedded': {'max': 0.0064,
                                 'min': 0.00068,
                                 'significant_figures': 2,
                                 'value': 0.0017},
                    'unit': 'kgSbeq',
                    'use': 'not implemented'},
            'gwp': {'description': 'Total climate change',
                    'embedded': {'max': 210.0,
                                 'min': 10.0,
                                 'significant_figures': 2,
                                 'value': 47.0},
                    'unit': 'kgCO2eq',
                    'use': 'not implemented'},
            'pe': {'description': 'Consumption of primary energy',
                   'embedded': {'max': 2620.0,
                                'min': 128.0,
                                'significant_figures': 3,
                                'value': 586.0},
                   'unit': 'MJ',
                   'use': 'not implemented'}}

def test_bottom_up_component_ram_empty(empty_ram_model):
    assert bottom_up(empty_ram_model, allocation=Allocation.TOTAL) == \
           {'adp': {'description': 'Use of minerals and fossil ressources',
                    'embedded': {'max': 0.065,
                                 'min': 0.0018,
                                 'significant_figures': 2,
                                 'value': 0.0049},
                    'unit': 'kgSbeq',
                    'use': {'max': 0.000211,
                            'min': 1.2e-10,
                            'significant_figures': 3,
                            'value': 5.11e-06}},
            'gwp': {'description': 'Total climate change',
                    'embedded': {'max': 2200.0,
                                 'min': 7.4,
                                 'significant_figures': 2,
                                 'value': 120.0},
                    'unit': 'kgCO2eq',
                    'use': {'max': 720.0,
                            'min': 0.00021,
                            'significant_figures': 2,
                            'value': 30.0}},
            'pe': {'description': 'Consumption of primary energy',
                   'embedded': {'max': 27000.0,
                                'min': 100.0,
                                'significant_figures': 2,
                                'value': 1500.0},
                   'unit': 'MJ',
                   'use': {'max': 372700.0,
                           'min': 0.0001181,
                           'significant_figures': 4,
                           'value': 1025.0}}}


def test_bottom_up_component_ram_complete(complete_ram_model):
    assert bottom_up(complete_ram_model, allocation=Allocation.TOTAL) == \
           {'adp': {'description': 'Use of minerals and fossil ressources',
                    'embedded': {'max': 0.034,
                                 'min': 0.034,
                                 'significant_figures': 2,
                                 'value': 0.034},
                    'unit': 'kgSbeq',
                    'use': {'max': 0.00254,
                            'min': 1.44e-09,
                            'significant_figures': 3,
                            'value': 6.13e-05}},
            'gwp': {'description': 'Total climate change',
                    'embedded': {'max': 530.0,
                                 'min': 530.0,
                                 'significant_figures': 2,
                                 'value': 530.0},
                    'unit': 'kgCO2eq',
                    'use': {'max': 8600.0,
                            'min': 0.0025,
                            'significant_figures': 2,
                            'value': 360.0}},
            'pe': {'description': 'Consumption of primary energy',
                   'embedded': {'max': 6700.0,
                                'min': 6700.0,
                                'significant_figures': 2,
                                'value': 6700.0},
                   'unit': 'MJ',
                   'use': {'max': 4472000.0,
                           'min': 0.001418,
                           'significant_figures': 4,
                           'value': 12300.0}}}

def test_bottom_up_component_ram_incomplete(incomplete_ram_model):
    assert bottom_up(incomplete_ram_model, allocation=Allocation.TOTAL) == \
           {'adp': {'description': 'Use of minerals and fossil ressources',
                    'embedded': {'max': 0.14,
                                 'min': 0.021,
                                 'significant_figures': 2,
                                 'value': 0.059},
                    'unit': 'kgSbeq',
                    'use': {'max': 0.00254,
                            'min': 1.44e-09,
                            'significant_figures': 3,
                            'value': 6.13e-05}},
            'gwp': {'description': 'Total climate change',
                    'embedded': {'max': 4300.0,
                                 'min': 100.0,
                                 'significant_figures': 2,
                                 'value': 1400.0},
                    'unit': 'kgCO2eq',
                    'use': {'max': 8600.0,
                            'min': 0.0025,
                            'significant_figures': 2,
                            'value': 360.0}},
            'pe': {'description': 'Consumption of primary energy',
                   'embedded': {'max': 53000.0,
                                'min': 1400.0,
                                'significant_figures': 2,
                                'value': 18000.0},
                   'unit': 'MJ',
                   'use': {'max': 4472000.0,
                           'min': 0.001418,
                           'significant_figures': 4,
                           'value': 12300.0}}}


def test_bottom_up_component_power_supply_complete(complete_power_supply_model):
    assert bottom_up(complete_power_supply_model, allocation=Allocation.TOTAL) == \
           {'adp': {'description': 'Use of minerals and fossil ressources',
                    'embedded': {'max': 0.05,
                                 'min': 0.05,
                                 'significant_figures': 2,
                                 'value': 0.05},
                    'unit': 'kgSbeq',
                    'use': 'not implemented'},
            'gwp': {'description': 'Total climate change',
                    'embedded': {'max': 145.0,
                                 'min': 145.0,
                                 'significant_figures': 3,
                                 'value': 145.0},
                    'unit': 'kgCO2eq',
                    'use': 'not implemented'},
            'pe': {'description': 'Consumption of primary energy',
                   'embedded': {'max': 2100.0,
                                'min': 2100.0,
                                'significant_figures': 3,
                                'value': 2100.0},
                   'unit': 'MJ',
                   'use': 'not implemented'}}


def test_bottom_up_component_power_supply_empty(empty_power_supply_model):
    assert bottom_up(empty_power_supply_model, allocation=Allocation.TOTAL) == \
           {'adp': {'description': 'Use of minerals and fossil ressources',
                    'embedded': {'max': 0.042,
                                    'min': 0.0083,
                                    'significant_figures': 2,
                                    'value': 0.025},
                    'unit': 'kgSbeq',
                    'use': 'not implemented'},
            'gwp': {'description': 'Total climate change',
                    'embedded': {'max': 122.0,
                                    'min': 24.3,
                                    'significant_figures': 3,
                                    'value': 72.7},
                    'unit': 'kgCO2eq',
                    'use': 'not implemented'},
            'pe': {'description': 'Consumption of primary energy',
                   'embedded': {'max': 1760.0,
                                   'min': 352.0,
                                   'significant_figures': 3,
                                   'value': 1050.0},
                   'unit': 'MJ',
                   'use': 'not implemented'}}

def test_bottom_up_component_hdd(hdd_model):
    assert bottom_up(hdd_model, allocation=Allocation.TOTAL) == \
           {'adp': {'description': 'Use of minerals and fossil ressources',
                    'embedded': {'max': 0.00025,
                                    'min': 0.00025,
                                    'significant_figures': 2,
                                    'value': 0.00025},
                    'unit': 'kgSbeq',
                    'use': 'not implemented'},
            'gwp': {'description': 'Total climate change',
                    'embedded': {'max': 31.1,
                                    'min': 31.1,
                                    'significant_figures': 3,
                                    'value': 31.1},
                    'unit': 'kgCO2eq',
                    'use': 'not implemented'},
            'pe': {'description': 'Consumption of primary energy',
                   'embedded': {'max': 276.0,
                                   'min': 276.0,
                                   'significant_figures': 3,
                                   'value': 276.0},
                   'unit': 'MJ',
                   'use': 'not implemented'}}

def test_bottom_up_component_motherboard(motherboard_model):
    assert bottom_up(motherboard_model, allocation=Allocation.TOTAL) == \
           {'adp': {'description': 'Use of minerals and fossil ressources',
                    'embedded': {'max': 0.00369,
                                    'min': 0.00369,
                                    'significant_figures': 3,
                                    'value': 0.00369},
                    'unit': 'kgSbeq',
                    'use': 'not implemented'},
            'gwp': {'description': 'Total climate change',
                    'embedded': {'max': 66.1,
                                    'min': 66.1,
                                    'significant_figures': 3,
                                    'value': 66.1},
                    'unit': 'kgCO2eq',
                    'use': 'not implemented'},
            'pe': {'description': 'Consumption of primary energy',
                   'embedded': {'max': 836.0,
                                   'min': 836.0,
                                   'significant_figures': 3,
                                   'value': 836.0},
                   'unit': 'MJ',
                   'use': 'not implemented'}}

def test_bottom_up_component_empty_case(empty_case_model):
    assert bottom_up(empty_case_model, allocation=Allocation.TOTAL) == \
           {'adp': {'description': 'Use of minerals and fossil ressources',
                    'embedded': {'max': 0.0277,
                              'min': 0.0202,
                              'significant_figures': 3,
                              'value': 0.0202},
                    'unit': 'kgSbeq',
                    'use': 'not implemented'},
            'gwp': {'description': 'Total climate change',
                    'embedded': {'max': 150.0,
                              'min': 85.9,
                              'significant_figures': 3,
                              'value': 150.0},
                    'unit': 'kgCO2eq',
                    'use': 'not implemented'},
            'pe': {'description': 'Consumption of primary energy',
                   'embedded': {'max': 2200.0,
                             'min': 1229.0,
                             'significant_figures': 4,
                             'value': 2200.0},
                   'unit': 'MJ',
                   'use': 'not implemented'}}


def test_bottom_up_component_blade_case(blade_case_model):
    assert bottom_up(blade_case_model, allocation=Allocation.TOTAL) == \
           {'adp': {'description': 'Use of minerals and fossil ressources',
                    'embedded': {'max': 0.0277,
                              'min': 0.0277,
                              'significant_figures': 3,
                              'value': 0.0277},
                    'unit': 'kgSbeq',
                    'use': 'not implemented'},
            'gwp': {'description': 'Total climate change',
                    'embedded': {'max': 85.9,
                              'min': 85.9,
                              'significant_figures': 3,
                              'value': 85.9},
                    'unit': 'kgCO2eq',
                    'use': 'not implemented'},
            'pe': {'description': 'Consumption of primary energy',
                   'embedded': {'max': 1230.0,
                             'min': 1230.0,
                             'significant_figures': 3,
                             'value': 1230.0},
                   'unit': 'MJ',
                   'use': 'not implemented'}}


def test_bottom_up_component_assembly(assembly_model):
    assert bottom_up(assembly_model, allocation=Allocation.TOTAL) == \
           {'adp': {'description': 'Use of minerals and fossil ressources',
                    'embedded': {'max': 1.41e-06,
                                    'min': 1.41e-06,
                                    'significant_figures': 3,
                                    'value': 1.41e-06},
                    'unit': 'kgSbeq',
                    'use': 'not implemented'},
            'gwp': {'description': 'Total climate change',
                    'embedded': {'max': 6.68,
                                    'min': 6.68,
                                    'significant_figures': 3,
                                    'value': 6.68},
                    'unit': 'kgCO2eq',
                    'use': 'not implemented'},
            'pe': {'description': 'Consumption of primary energy',
                   'embedded': {'max': 68.6,
                                   'min': 68.6,
                                   'significant_figures': 3,
                                   'value': 68.6},
                   'unit': 'MJ',
                   'use': 'not implemented'}}