from boaviztapi.service.verbose import verbose_component, verbose_device


def test_verbose_component_cpu_1(complete_cpu_model):
    verbose = verbose_component(complete_cpu_model)
    assert verbose["core_units"] == {'status': 'INPUT', 'value': 24}
    assert verbose["die_size_per_core"] == {'status': 'INPUT', 'unit': 'mm2', 'value': 0.245}

    assert verbose["manufacture"] == {'adp': {'description': 'Use of minerals and fossil ressources',
                                              'max': 0.02,
                                              'min': 0.02,
                                              'significant_figures': 2,
                                              'unit': 'kgSbeq',
                                              'value': 0.041},
                                      'gwp': {'description': 'Effects on global warming',
                                              'max': 22.7,
                                              'min': 11.1,
                                              'significant_figures': 3,
                                              'unit': 'kgCO2eq',
                                              'value': 43.4},
                                      'pe': {'description': 'Consumption of primary energy',
                                             'max': 339.0,
                                             'min': 182.0,
                                             'significant_figures': 3,
                                             'unit': 'MJ',
                                             'value': 650.0}}

def test_verbose_component_cpu_2(incomplete_cpu_model):
    verbose = verbose_component(incomplete_cpu_model)
    assert verbose["core_units"] == {'status': 'INPUT', 'value': 12}
    assert verbose["family"] == {'status': 'INPUT', 'value': 'Skylake'}
    assert verbose["manufacture"] == {'adp': {'description': 'Use of minerals and fossil ressources',
                                              'max': 0.02,
                                              'min': 0.02,
                                              'significant_figures': 2,
                                              'unit': 'kgSbeq',
                                              'value': 0.02},
                                      'gwp': {'description': 'Effects on global warming',
                                              'max': 22.7,
                                              'min': 11.1,
                                              'significant_figures': 3,
                                              'unit': 'kgCO2eq',
                                              'value': 19.7},
                                      'pe': {'description': 'Consumption of primary energy',
                                             'max': 339.0,
                                             'min': 182.0,
                                             'significant_figures': 3,
                                             'unit': 'MJ',
                                             'value': 297.0}}


def test_verbose_component_ram(complete_ram_model):
    verbose = verbose_component(complete_ram_model)

    assert verbose["manufacture"] == {'adp': {'description': 'Use of minerals and fossil ressources',
                                              'max': 0.008,
                                              'min': 0.0023,
                                              'significant_figures': 2,
                                              'unit': 'kgSbeq',
                                              'value': 0.034},
                                      'gwp': {'description': 'Effects on global warming',
                                              'max': 230.0,
                                              'min': 27.0,
                                              'significant_figures': 2,
                                              'unit': 'kgCO2eq',
                                              'value': 530.0},
                                      'pe': {'description': 'Consumption of primary energy',
                                             'max': 2800.0,
                                             'min': 350.0,
                                             'significant_figures': 2,
                                             'unit': 'MJ',
                                             'value': 6700.0}}

    assert verbose["capacity"] == {'status': 'INPUT', 'unit': 'GB', 'value': 32}
    assert verbose["density"] == {'status': 'INPUT', 'unit': 'GB/cm2', 'value': 1.79}


def test_verbose_component_ssd(empty_ssd_model):
    assert verbose_component(empty_ssd_model) == {'capacity': {'max': 5000,
                                                               'min': 100,
                                                               'status': 'DEFAULT',
                                                               'unit': 'GB',
                                                               'value': 1000},
                                                  'density': {'max': 1,
                                                              'min': 0.1,
                                                              'status': 'DEFAULT',
                                                              'unit': 'GB/cm2',
                                                              'value': 48.5},
                                                  'manufacture': {'adp': {'description': 'Use of minerals and fossil ressources',
                                                                          'max': 0.32,
                                                                          'min': 0.064,
                                                                          'significant_figures': 2,
                                                                          'unit': 'kgSbeq',
                                                                          'value': 0.0019},
                                                                  'gwp': {'description': 'Effects on global warming',
                                                                          'max': 11000.0,
                                                                          'min': 2200.0,
                                                                          'significant_figures': 2,
                                                                          'unit': 'kgCO2eq',
                                                                          'value': 52.0},
                                                                  'pe': {'description': 'Consumption of primary energy',
                                                                         'max': 137000.0,
                                                                         'min': 27400.0,
                                                                         'significant_figures': 3,
                                                                         'unit': 'MJ',
                                                                         'value': 640.0}},
                                                  'units': {'max': 1, 'min': 1, 'status': 'DEFAULT', 'value': 1}}


def test_verbose_component_power_supply(empty_power_supply_model):
    assert verbose_component(empty_power_supply_model) == {'manufacture': {'adp': {'description': 'Use of minerals and fossil ressources',
                                                                                   'max': 0.042,
                                                                                   'min': 0.0083,
                                                                                   'significant_figures': 2,
                                                                                   'unit': 'kgSbeq',
                                                                                   'value': 0.025},
                                                                           'gwp': {'description': 'Effects on global warming',
                                                                                   'max': 122.0,
                                                                                   'min': 24.3,
                                                                                   'significant_figures': 3,
                                                                                   'unit': 'kgCO2eq',
                                                                                   'value': 72.7},
                                                                           'pe': {'description': 'Consumption of primary energy',
                                                                                  'max': 1760.0,
                                                                                  'min': 352.0,
                                                                                  'significant_figures': 3,
                                                                                  'unit': 'MJ',
                                                                                  'value': 1050.0}},
                                                           'unit_weight': {'max': 5,
                                                                           'min': 1,
                                                                           'status': 'DEFAULT',
                                                                           'unit': 'kg',
                                                                           'value': 2.99},
                                                           'units': {'max': 1, 'min': 1, 'status': 'DEFAULT', 'value': 1}}


def test_verbose_component_case(blade_case_model):
    assert verbose_component(blade_case_model) == {'case_type': {'status': 'INPUT', 'value': 'blade'},
                                                   'manufacture': {'adp': {'description': 'Use of minerals and fossil ressources',
                                                                           'max': 0.000714,
                                                                           'min': 0.000714,
                                                                           'significant_figures': 3,
                                                                           'unit': 'kgSbeq',
                                                                           'value': 0.0277},
                                                                   'gwp': {'description': 'Effects on global warming',
                                                                           'max': 32.8,
                                                                           'min': 32.8,
                                                                           'significant_figures': 3,
                                                                           'unit': 'kgCO2eq',
                                                                           'value': 85.9},
                                                                   'pe': {'description': 'Consumption of primary energy',
                                                                          'max': 462.0,
                                                                          'min': 462.0,
                                                                          'significant_figures': 3,
                                                                          'unit': 'MJ',
                                                                          'value': 1230.0}},
                                                   'units': {'max': 1, 'min': 1, 'status': 'DEFAULT', 'value': 1}}


def test_verbose_device_server_1(incomplete_server_model):
    verbose = verbose_device(incomplete_server_model)

    assert verbose["ASSEMBLY-1"] == {'manufacture': {'adp': {'description': 'Use of minerals and fossil ressources',
                                                             'max': 1.41e-06,
                                                             'min': 1.41e-06,
                                                             'significant_figures': 3,
                                                             'unit': 'kgSbeq',
                                                             'value': 1.41e-06},
                                                     'gwp': {'description': 'Effects on global warming',
                                                             'max': 6.68,
                                                             'min': 6.68,
                                                             'significant_figures': 3,
                                                             'unit': 'kgCO2eq',
                                                             'value': 6.68},
                                                     'pe': {'description': 'Consumption of primary energy',
                                                            'max': 68.6,
                                                            'min': 68.6,
                                                            'significant_figures': 3,
                                                            'unit': 'MJ',
                                                            'value': 68.6}},
                                     'units': {'max': 1, 'min': 1, 'status': 'DEFAULT', 'value': 1}}

    assert verbose["CASE-1"] == {'case_type': {'status': 'INPUT', 'value': 'rack'},
                                 'manufacture': {'adp': {'description': 'Use of minerals and fossil ressources',
                                                         'max': 0.0202,
                                                         'min': 0.0202,
                                                         'significant_figures': 3,
                                                         'unit': 'kgSbeq',
                                                         'value': 0.0202},
                                                 'gwp': {'description': 'Effects on global warming',
                                                         'max': 150.0,
                                                         'min': 150.0,
                                                         'significant_figures': 3,
                                                         'unit': 'kgCO2eq',
                                                         'value': 150.0},
                                                 'pe': {'description': 'Consumption of primary energy',
                                                        'max': 2200.0,
                                                        'min': 2200.0,
                                                        'significant_figures': 4,
                                                        'unit': 'MJ',
                                                        'value': 2200.0}},
                                 'units': {'max': 1, 'min': 1, 'status': 'DEFAULT', 'value': 1}}

    assert verbose["MOTHERBOARD-1"] == {'manufacture': {'adp': {'description': 'Use of minerals and fossil ressources',
                                                                'max': 0.00369,
                                                                'min': 0.00369,
                                                                'significant_figures': 3,
                                                                'unit': 'kgSbeq',
                                                                'value': 0.00369},
                                                        'gwp': {'description': 'Effects on global warming',
                                                                'max': 66.1,
                                                                'min': 66.1,
                                                                'significant_figures': 3,
                                                                'unit': 'kgCO2eq',
                                                                'value': 66.1},
                                                        'pe': {'description': 'Consumption of primary energy',
                                                               'max': 836.0,
                                                               'min': 836.0,
                                                               'significant_figures': 3,
                                                               'unit': 'MJ',
                                                               'value': 836.0}},
                                        'units': {'max': 1, 'min': 1, 'status': 'DEFAULT', 'value': 1}}

    assert verbose["POWER_SUPPLY-1"] == {'manufacture': {'adp': {'description': 'Use of minerals and fossil ressources',
                                                                 'max': 0.17,
                                                                 'min': 0.0083,
                                                                 'significant_figures': 2,
                                                                 'unit': 'kgSbeq',
                                                                 'value': 0.05},
                                                         'gwp': {'description': 'Effects on global warming',
                                                                 'max': 486.0,
                                                                 'min': 24.3,
                                                                 'significant_figures': 3,
                                                                 'unit': 'kgCO2eq',
                                                                 'value': 145.0},
                                                         'pe': {'description': 'Consumption of primary energy',
                                                                'max': 7040.0,
                                                                'min': 352.0,
                                                                'significant_figures': 3,
                                                                'unit': 'MJ',
                                                                'value': 2100.0}},
                                         'unit_weight': {'max': 5,
                                                         'min': 1,
                                                         'status': 'DEFAULT',
                                                         'unit': 'kg',
                                                         'value': 2.99},
                                         'units': {'max': 4, 'min': 1, 'status': 'DEFAULT', 'value': 2}}


def test_verbose_device_server_2(dell_r740_model):
    verbose = verbose_device(dell_r740_model)
    assert verbose["ASSEMBLY-1"] == {'manufacture': {'adp': {'description': 'Use of minerals and fossil ressources',
                                                             'max': 1.41e-06,
                                                             'min': 1.41e-06,
                                                             'significant_figures': 3,
                                                             'unit': 'kgSbeq',
                                                             'value': 1.41e-06},
                                                     'gwp': {'description': 'Effects on global warming',
                                                             'max': 6.68,
                                                             'min': 6.68,
                                                             'significant_figures': 3,
                                                             'unit': 'kgCO2eq',
                                                             'value': 6.68},
                                                     'pe': {'description': 'Consumption of primary energy',
                                                            'max': 68.6,
                                                            'min': 68.6,
                                                            'significant_figures': 3,
                                                            'unit': 'MJ',
                                                            'value': 68.6}},
                                     'units': {'max': 1, 'min': 1, 'status': 'DEFAULT', 'value': 1}}

    assert verbose["CASE-1"] == {'case_type': {'status': 'INPUT', 'value': 'rack'},
                                 'manufacture': {'adp': {'description': 'Use of minerals and fossil ressources',
                                                         'max': 0.0202,
                                                         'min': 0.0202,
                                                         'significant_figures': 3,
                                                         'unit': 'kgSbeq',
                                                         'value': 0.0202},
                                                 'gwp': {'description': 'Effects on global warming',
                                                         'max': 150.0,
                                                         'min': 150.0,
                                                         'significant_figures': 3,
                                                         'unit': 'kgCO2eq',
                                                         'value': 150.0},
                                                 'pe': {'description': 'Consumption of primary energy',
                                                        'max': 2200.0,
                                                        'min': 2200.0,
                                                        'significant_figures': 4,
                                                        'unit': 'MJ',
                                                        'value': 2200.0}},
                                 'units': {'max': 1, 'min': 1, 'status': 'DEFAULT', 'value': 1}}

    assert verbose["MOTHERBOARD-1"] == {'manufacture': {'adp': {'description': 'Use of minerals and fossil ressources',
                                                                'max': 0.00369,
                                                                'min': 0.00369,
                                                                'significant_figures': 3,
                                                                'unit': 'kgSbeq',
                                                                'value': 0.00369},
                                                        'gwp': {'description': 'Effects on global warming',
                                                                'max': 66.1,
                                                                'min': 66.1,
                                                                'significant_figures': 3,
                                                                'unit': 'kgCO2eq',
                                                                'value': 66.1},
                                                        'pe': {'description': 'Consumption of primary energy',
                                                               'max': 836.0,
                                                               'min': 836.0,
                                                               'significant_figures': 3,
                                                               'unit': 'MJ',
                                                               'value': 836.0}},
                                        'units': {'max': 1, 'min': 1, 'status': 'DEFAULT', 'value': 1}}

    assert verbose["POWER_SUPPLY-1"] == {'manufacture': {'adp': {'description': 'Use of minerals and fossil ressources',
                                                                 'max': 0.042,
                                                                 'min': 0.0083,
                                                                 'significant_figures': 2,
                                                                 'unit': 'kgSbeq',
                                                                 'value': 0.05},
                                                         'gwp': {'description': 'Effects on global warming',
                                                                 'max': 122.0,
                                                                 'min': 24.3,
                                                                 'significant_figures': 3,
                                                                 'unit': 'kgCO2eq',
                                                                 'value': 145.0},
                                                         'pe': {'description': 'Consumption of primary energy',
                                                                'max': 1760.0,
                                                                'min': 352.0,
                                                                'significant_figures': 3,
                                                                'unit': 'MJ',
                                                                'value': 2100.0}},
                                         'unit_weight': {'status': 'INPUT', 'unit': 'kg', 'value': 2.99},
                                         'units': {'status': 'INPUT', 'value': 2}}