name: build_client_sdk

on:
  push:
    branches: [ dev ]
    paths-ignore:
      - 'docs_src/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'CITATION'
      - 'book.toml'
      - 'CONTRIBUTING.md'
  pull_request:
    branches: [ dev ]

env:
  CARGO_TERM_COLOR: always
  API_VERSION:  "0.42"

jobs:
  build:
    name: build_python_client_sdk
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies (awxkit)
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install requirements
        run: |
          sudo apt install docker.io containerd runc wget -y
      - name: Run the API locally
        run: |
          python3 setup.py sdist
          docker build --build-arg "${API_VERSION}" . --file Dockerfile --tag boaviztapi:latest
          docker run -p "5000:5000" --name=boaviztapi -tid boaviztapi:latest
      - name: Get the openapi.json definition
        run: |
          wget http://localhost:5000/openapi.json
          docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate -i /local/openapi.json -g python -o /local/python-client
