name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: GitHub Action for pytest
      uses: cclauss/GitHub-Action-for-pytest@0.5.0

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}  

    - name: Build the api Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/boavizta/tools-api:latest
      
    - name : Tag api Docker image
      run: docker tag ghcr.io/boavizta/tools-api:latest ghcr.io/boavizta/tools-api:$(date +%s)
      
    - name: Push api images
      run: docker push -a ghcr.io/boavizta/tools-api

    - name: Build doc the Docker image
      run: docker build . --file docs/Dockerfile --tag ghcr.io/boavizta/tools-doc:latest

    - name: Tag doc the Docker image
      run: docker tag ghcr.io/boavizta/tools-doc:latest ghcr.io/boavizta/tools-doc:$(date +%s)

    - name: Push doc images
      run: docker push -a ghcr.io/boavizta/tools-doc
