name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}  
       
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:latest
      
    - name : tag the Docker image
      run: docker tag ghcr.io/Boavizta/tools-api:latest ghcr.io/Boavizta/tools-api:$(date +%s)
      
    - name: Push images 
      run: docker push -a ghcr.io/Boavizta/tools-api
