name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: doc.api.boavizta.org
          CONFIG_FILE: docs/mkdocs.yml
          EXTRA_PACKAGES: build-base
          REQUIREMENTS: docs/requirements.txt
      - name: change permissions
        run: sudo chown -R $(whoami) .git
      - name: set custom domain
        run: |
         git fetch origin gh-pages
         git checkout gh-pages
         echo 'doc.api.boavizta.org' > CNAME
         git add CNAME
         git commit -m "adding CNAME"
         git push origin gh-pages
