name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r docs/requirements.txt

      - name: Deploy
        run: mkdocs gh-deploy  --verbose --force --config-file docs/mkdocs.yml

      - name: force CNAME # we don't understand why CNAME in docs is not copied in gh-pages
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          sudo chown -R $(whoami) .git
          git fetch origin gh-pages
          git checkout gh-pages
          echo "doc.api.boavizta.org" > CNAME
          git add CNAME
          git commit --amend --no-edit
          git push origin gh-pages --force
