name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r docs/requirements.txt

      - name: Deploy
        run: mkdocs gh-deploy --force --config-file docs/mkdocs.yml --cname doc.api.boavizta.org
